/* Autogenerated file. Do not edit manually. */

package datamod

import (
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/concrete/codegen/datamod/codec"
	"github.com/ethereum/go-ethereum/concrete/crypto"
	"github.com/ethereum/go-ethereum/concrete/lib"
)

// Reference imports to suppress errors if they are not used.
var (
	_ = crypto.Keccak256
	_ = big.NewInt
	_ = common.Big1
	_ = codec.EncodeAddress
)

// var (
//	MetaDefaultKey = crypto.Keccak256([]byte("datamod.v1.Meta"))
// )

func MetaDefaultKey() []byte {
	return crypto.Keccak256([]byte("datamod.v1.Meta"))
}

type MetaRow struct {
	lib.IDatastoreStruct
}

func NewMetaRow(dsSlot lib.DatastoreSlot) *MetaRow {
	sizes := []int{1, 1}
	return &MetaRow{lib.NewDatastoreStruct(dsSlot, sizes)}
}

func (v *MetaRow) Get() (
	maxBodyCount uint8,
	bodyCount uint8,
) {
	return codec.DecodeSmallUint8(1, v.GetField(0)),
		codec.DecodeSmallUint8(1, v.GetField(1))
}

func (v *MetaRow) Set(
	maxBodyCount uint8,
	bodyCount uint8,
) {
	v.SetField(0, codec.EncodeSmallUint8(1, maxBodyCount))
	v.SetField(1, codec.EncodeSmallUint8(1, bodyCount))
}

func (v *MetaRow) GetMaxBodyCount() uint8 {
	data := v.GetField(0)
	return codec.DecodeSmallUint8(1, data)
}

func (v *MetaRow) SetMaxBodyCount(value uint8) {
	data := codec.EncodeSmallUint8(1, value)
	v.SetField(0, data)
}

func (v *MetaRow) GetBodyCount() uint8 {
	data := v.GetField(1)
	return codec.DecodeSmallUint8(1, data)
}

func (v *MetaRow) SetBodyCount(value uint8) {
	data := codec.EncodeSmallUint8(1, value)
	v.SetField(1, data)
}

type Meta struct {
	dsSlot lib.DatastoreSlot
}

func NewMeta(ds lib.Datastore) *Meta {
	dsSlot := ds.Get(MetaDefaultKey())
	return &Meta{dsSlot}
}

func NewMetaFromSlot(dsSlot lib.DatastoreSlot) *Meta {
	return &Meta{dsSlot}
}
func (m *Meta) Get() *MetaRow {
	return NewMetaRow(m.dsSlot)
}
