/* Autogenerated file. Do not edit manually. */

package archmod

import (
	"github.com/ethereum/go-ethereum/common"
)

var (
	_ = common.Big1
)

/*
Table    KeySize  ValueSize
AddBody  0        20
*/

type ActionData_AddBody struct {
	X  int32  `json:"x"`
	Y  int32  `json:"y"`
	R  uint32 `json:"r"`
	Vx int32  `json:"vx"`
	Vy int32  `json:"vy"`
}

func (row *ActionData_AddBody) GetX() int32 {
	return row.X
}

func (row *ActionData_AddBody) GetY() int32 {
	return row.Y
}

func (row *ActionData_AddBody) GetR() uint32 {
	return row.R
}

func (row *ActionData_AddBody) GetVx() int32 {
	return row.Vx
}

func (row *ActionData_AddBody) GetVy() int32 {
	return row.Vy
}
