/* Autogenerated file. Do not edit manually. */

package archmod

import (
	"github.com/ethereum/go-ethereum/common"
)

var (
	_ = common.Big1
)

/*
Table      KeySize  ValueSize
AddPlayer  0        4
Move       0        3
*/

type ActionData_AddPlayer struct {
	X int16 `json:"x"`
	Y int16 `json:"y"`
}

func (row *ActionData_AddPlayer) GetX() int16 {
	return row.X
}

func (row *ActionData_AddPlayer) GetY() int16 {
	return row.Y
}

type ActionData_Move struct {
	PlayerId  uint16 `json:"playerId"`
	Direction uint8  `json:"direction"`
}

func (row *ActionData_Move) GetPlayerId() uint16 {
	return row.PlayerId
}

func (row *ActionData_Move) GetDirection() uint8 {
	return row.Direction
}
