/* Autogenerated file. Do not edit manually. */

package archmod

import (
	"github.com/ethereum/go-ethereum/common"
)

var (
	_ = common.Big1
)

/*
Table    KeySize  ValueSize
Meta     0        12
Players  2        4
Board    4        2
*/

type RowData_Meta struct {
	StartBlock  uint64 `json:"startBlock"`
	MaxPlayers  uint16 `json:"maxPlayers"`
	PlayerCount uint16 `json:"playerCount"`
}

func (row *RowData_Meta) GetStartBlock() uint64 {
	return row.StartBlock
}

func (row *RowData_Meta) GetMaxPlayers() uint16 {
	return row.MaxPlayers
}

func (row *RowData_Meta) GetPlayerCount() uint16 {
	return row.PlayerCount
}

type RowData_Players struct {
	X int16 `json:"x"`
	Y int16 `json:"y"`
}

func (row *RowData_Players) GetX() int16 {
	return row.X
}

func (row *RowData_Players) GetY() int16 {
	return row.Y
}

type RowData_Board struct {
	PlayerId uint16 `json:"playerId"`
}

func (row *RowData_Board) GetPlayerId() uint16 {
	return row.PlayerId
}
