/* Autogenerated file. Do not edit manually. */

package archmod

import (
	"github.com/ethereum/go-ethereum/common"
)

var (
	_ = common.Big1
)

/*
Table   KeySize  ValueSize
Meta    0        2
Bodies  1        10
*/

type RowData_Meta struct {
	MaxBodyCount uint8 `json:"maxBodyCount"`
	BodyCount    uint8 `json:"bodyCount"`
}

func (row *RowData_Meta) GetMaxBodyCount() uint8 {
	return row.MaxBodyCount
}

func (row *RowData_Meta) GetBodyCount() uint8 {
	return row.BodyCount
}

type RowData_Bodies struct {
	X  int16  `json:"x"`
	Y  int16  `json:"y"`
	M  uint16 `json:"m"`
	Vx int16  `json:"vx"`
	Vy int16  `json:"vy"`
}

func (row *RowData_Bodies) GetX() int16 {
	return row.X
}

func (row *RowData_Bodies) GetY() int16 {
	return row.Y
}

func (row *RowData_Bodies) GetM() uint16 {
	return row.M
}

func (row *RowData_Bodies) GetVx() int16 {
	return row.Vx
}

func (row *RowData_Bodies) GetVy() int16 {
	return row.Vy
}
