/* Autogenerated file. Do not edit manually. */

package archmod

import (
	"reflect"

	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/concrete/lib"

	archtypes "github.com/concrete-eth/archetype/types"

	"github.com/concrete-eth/archetype/example/gogen/datamod"
)

var (
	_ = common.Big1
)

/*
Table    KeySize  ValueSize
Config   0        9
Players  1        5
*/

const (
	TableId_Config uint8 = iota
	TableId_Players
)

var Tables = archtypes.TableSpecs{
	Tables:  tableMap,
	ABI:     nil,
	GetData: getData,
}

var tableMap = archtypes.TableMap{
	TableId_Config: {
		Id:         TableId_Config,
		Name:       "Config",
		MethodName: "getConfigRow",
		Keys:       []string{},
		Columns: []string{
			"startBlock",
			"maxPlayers",
		},
		Type: reflect.TypeOf(RowData_Config{}),
	},
	TableId_Players: {
		Id:         TableId_Players,
		Name:       "Players",
		MethodName: "getPlayersRow",
		Keys: []string{
			"playerId",
		},
		Columns: []string{
			"x",
			"y",
			"health",
		},
		Type: reflect.TypeOf(RowData_Players{}),
	},
}

func getData(datastore lib.Datastore, method *abi.Method, args []interface{}) (interface{}, bool) {
	switch method.Name {
	case "getConfigRow":
		row := datamod.NewConfig(datastore).Get()
		return RowData_Config{
			StartBlock: row.GetStartBlock(),
			MaxPlayers: row.GetMaxPlayers(),
		}, true
	case "getPlayersRow":
		row := datamod.NewPlayers(datastore).Get(
			args[0].(uint8),
		)
		return RowData_Players{
			X:      row.GetX(),
			Y:      row.GetY(),
			Health: row.GetHealth(),
		}, true
	}
	return nil, false
}

type State struct {
	datastore lib.Datastore
	config    *datamod.Config
	players   *datamod.Players
}

func NewState(datastore lib.Datastore) *State {
	return &State{
		datastore: datastore,
	}
}

func (s *State) Config() *datamod.Config {
	if s.config == nil {
		s.config = datamod.NewConfig(s.datastore)
	}
	return s.config
}

func (s *State) Players() *datamod.Players {
	if s.players == nil {
		s.players = datamod.NewPlayers(s.datastore)
	}
	return s.players
}

func (s *State) GetConfigRow() *datamod.ConfigRow {
	return s.Config().Get()
}

func (s *State) GetPlayersRow(
	playerId uint8,
) *datamod.PlayersRow {
	return s.Players().Get(
		playerId,
	)
}

type RowData_Config struct {
	StartBlock uint64 `json:"startBlock"`
	MaxPlayers uint8  `json:"maxPlayers"`
}

func (row *RowData_Config) GetStartBlock() uint64 {
	return row.StartBlock
}

func (row *RowData_Config) GetMaxPlayers() uint8 {
	return row.MaxPlayers
}

type RowData_Players struct {
	X      int16 `json:"x"`
	Y      int16 `json:"y"`
	Health uint8 `json:"health"`
}

func (row *RowData_Players) GetX() int16 {
	return row.X
}

func (row *RowData_Players) GetY() int16 {
	return row.Y
}

func (row *RowData_Players) GetHealth() uint8 {
	return row.Health
}
