/* Autogenerated file. Do not edit manually. */

package archmod

import (
	"github.com/ethereum/go-ethereum/common"
)

var (
	_ = common.Big1
)

/*
Table   KeySize  ValueSize
Meta    0        2
Bodies  1        28
*/

type RowData_Meta struct {
	MaxBodyCount uint8 `json:"maxBodyCount"`
	BodyCount    uint8 `json:"bodyCount"`
}

func (row *RowData_Meta) GetMaxBodyCount() uint8 {
	return row.MaxBodyCount
}

func (row *RowData_Meta) GetBodyCount() uint8 {
	return row.BodyCount
}

type RowData_Bodies struct {
	X  int32  `json:"x"`
	Y  int32  `json:"y"`
	R  uint32 `json:"r"`
	Vx int32  `json:"vx"`
	Vy int32  `json:"vy"`
	Ax int32  `json:"ax"`
	Ay int32  `json:"ay"`
}

func (row *RowData_Bodies) GetX() int32 {
	return row.X
}

func (row *RowData_Bodies) GetY() int32 {
	return row.Y
}

func (row *RowData_Bodies) GetR() uint32 {
	return row.R
}

func (row *RowData_Bodies) GetVx() int32 {
	return row.Vx
}

func (row *RowData_Bodies) GetVy() int32 {
	return row.Vy
}

func (row *RowData_Bodies) GetAx() int32 {
	return row.Ax
}

func (row *RowData_Bodies) GetAy() int32 {
	return row.Ay
}
