/* Autogenerated file. Do not edit manually. */

package archmod

import (
	"reflect"

	archtypes "github.com/concrete-eth/archetype/types"
	"github.com/ethereum/go-ethereum/concrete/lib"

	contract "github.com/concrete-eth/archetype/example/gogen/abigen/tables"
	mod "github.com/concrete-eth/archetype/example/gogen/datamod"
)

var TablesABIJson = contract.ContractABI

var TablesSchemaJson = `{
    "config": {
        "schema": {
            "startBlock": "uint64",
            "maxPlayers": "uint8"
        }
    },
    "players": {
        "keySchema": {
            "playerId": "uint8"
        },
        "schema": {
            "x": "int16",
            "y": "int16",
            "health": "uint8"
        }
    }
}`

var TableSpecs archtypes.TableSpecs

func init() {
	types := map[string]reflect.Type{
		"Config":  reflect.TypeOf(RowData_Config{}),
		"Players": reflect.TypeOf(RowData_Players{}),
	}
	getters := map[string]archtypes.GetterFn{
		"Config": func(ds lib.Datastore) interface{} {
			return mod.NewConfig(ds)
		},
		"Players": func(ds lib.Datastore) interface{} {
			return mod.NewPlayers(ds)
		},
	}
	var err error
	if TableSpecs, err = archtypes.NewTableSpecsFromRaw(TablesABIJson, TablesSchemaJson, types, getters); err != nil {
		panic(err)
	}
}
