// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

enum ActionId {
{{- $length := len .Schemas }}
{{- range $index, $element := .Schemas }}
    {{.Name}}{{if lt $index (_sub $length 1)}},{{ end }}
{{- end }}
}
{{ range .Schemas }}
{{- if .Values }}
struct ActionData_{{.Name}} {
    {{- range .Values }}
    {{.Type.SolType}} {{.Name}};
    {{- end }}
}
{{ end }}
{{- end }}
interface {{.Name}} {
    event {{.ArchParams.ActionExecutedEventName}}(uint8 actionId, bytes data);
{{ range .Schemas }}
    {{- if .Values }}
    function {{_actionMethodName .Name}}(ActionData_{{.Name}} memory action) external;
    {{- else }}
    function {{_actionMethodName .Name}}() external;
    {{- end }}
{{- end }}
}
