// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

{{ range $schema := .Schemas }}
{{- if $schema.Values }}
struct {{ActionStructNameFn $schema.Name}} {
    {{- range $value := $schema.Values }}
    {{$value.Type.SolType}} {{$value.Name}};
    {{- end }}
}
{{ end }}
{{- end }}

interface {{.Name}} {
    event {{$.ArchParams.ActionExecutedEventName}}(bytes4 actionId, bytes data);
{{ range $schema := .Schemas }}
    {{- if $schema.Values }}
    function {{ActionMethodNameFn $schema.Name}}({{ActionStructNameFn $schema.Name}} memory action) external;
    {{- else }}
    function {{ActionMethodNameFn $schema.Name}}() external;
    {{- end }}
{{- end }}
}

