/* Autogenerated file. Do not edit manually. */

package archmod

import (
	"github.com/ethereum/go-ethereum/common"
)

var (
	_ = common.Big1
)

/*
Table  KeySize  ValueSize
Add    0        2
*/

type ActionData_Add struct {
	Summand int16 `json:"summand"`
}

func (row *ActionData_Add) GetSummand() int16 {
	return row.Summand
}
