/* Autogenerated file. Do not edit manually. */

package archmod

import (
	"reflect"

	"github.com/concrete-eth/archetype/arch"

	contract "github.com/concrete-eth/archetype/testutils/gogen/abigen/actions"
)

var ActionsABIJson = contract.ContractABI

var ActionsSchemaJson = `{
    "add": {
        "schema": {
            "summand": "int16"
        }
    }
}`

var ActionSpecs arch.ActionSpecs

func init() {
	types := map[string]reflect.Type{
		"Add":  reflect.TypeOf(ActionData_Add{}),
		"Tick": reflect.TypeOf(arch.CanonicalTickAction{}),
	}
	var err error
	if ActionSpecs, err = arch.NewActionSpecsFromRaw(ActionsABIJson, ActionsSchemaJson, types); err != nil {
		panic(err)
	}
}

type IActions interface {
	Add(action *ActionData_Add) error
	Tick()
}
