/* Autogenerated file. Do not edit manually. */

package archmod

import (
	"reflect"

	archtypes "github.com/concrete-eth/archetype/types"

	contract "github.com/concrete-eth/archetype/testutils/gogen/abigen/actions"
)

var ActionsABIJson = contract.ContractABI

var ActionsSchemaJson = `{
    "add": {
        "schema": {
            "summand": "int16"
        }
    }
}`

var ActionSpecs archtypes.ActionSpecs

func init() {
	types := map[string]reflect.Type{
		"Add": reflect.TypeOf(ActionData_Add{}),
	}
	var err error
	if ActionSpecs, err = archtypes.NewActionSpecsFromRaw(ActionsABIJson, ActionsSchemaJson, types); err != nil {
		panic(err)
	}
}

type IActions interface {
	Add(action *ActionData_Add) error
}
