/* Autogenerated file. Do not edit manually. */

package archmod

import (
	"reflect"

	archtypes "github.com/concrete-eth/archetype/types"

	contract "github.com/concrete-eth/archetype/testutils/gogen/abigen/tables"
	mod "github.com/concrete-eth/archetype/testutils/gogen/datamod"
)

var TablesABIJson = contract.ContractABI

var TablesSchemaJson = `{
    "counter": {
        "schema": {
            "value": "int16"
        }
    }
}`

var TableSpecs archtypes.TableSpecs

func init() {
	types := map[string]reflect.Type{
		"Counter": reflect.TypeOf(RowData_Counter{}),
	}
	getters := map[string]interface{}{
		"Counter": mod.NewCounter,
	}
	var err error
	if TableSpecs, err = archtypes.NewTableSpecsFromRaw(TablesABIJson, TablesSchemaJson, types, getters); err != nil {
		panic(err)
	}
}
