/* Autogenerated file. Do not edit manually. */

package archmod

import (
	"github.com/ethereum/go-ethereum/common"
)

var (
	_ = common.Big1
)

/*
Table    KeySize  ValueSize
Counter  0        2
*/

type RowData_Counter struct {
	Value int16 `json:"value"`
}

func (row *RowData_Counter) GetValue() int16 {
	return row.Value
}
