// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

struct ActionData_AddPlayer {
    int16 x;
    int16 y;
}

struct ActionData_Move {
    uint16 playerId;
    uint8 direction;
}

interface IActions {
    event ActionExecuted(bytes4 actionId, bytes data);

    function addPlayer(ActionData_AddPlayer memory action) external;
    function move(ActionData_Move memory action) external;
}
