// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

struct ActionData_AddBody {
    int32 x;
    int32 y;
    uint32 r;
    int32 vx;
    int32 vy;
}

interface IActions {
    event ActionExecuted(bytes4 actionId, bytes data);

    function tick() external;

    function addBody(ActionData_AddBody memory action) external;
}
