// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

struct ActionData_AddBody {
    int16 x;
    int16 y;
    uint16 m;
    int16 vx;
    int16 vy;
}

interface IActions {
    event ActionExecuted(bytes4 actionId, bytes data);

    function addBody(ActionData_AddBody memory action) external;
}
