// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

struct RowData_Meta {
    uint64 startBlock;
    uint16 maxPlayers;
    uint16 playerCount;
}

struct RowData_Players {
    int16 x;
    int16 y;
}

struct RowData_Board {
    uint16 playerId;
}

interface ITables {
    function getMeta() external view returns (RowData_Meta memory);
    function getPlayers(
        uint16 playerId
    ) external view returns (RowData_Players memory);
    function getBoard(
        int16 x,
        int16 y
    ) external view returns (RowData_Board memory);
}
