// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */


import "./IActions.sol";
import "arch/ArchBase.sol";

abstract contract Entrypoint is ArchBase {
    function executeMultipleActions(
        uint32[] memory actionIds,
        uint8[] memory actionCount,
        bytes[] memory actionData
    ) external {
        uint256 actionIdx = 0;
        for (uint256 i = 0; i < actionIds.length; i++) {
            uint256 numActions = uint256(actionCount[i]);
            for (uint256 j = actionIdx; j < actionIdx + numActions; j++) {
                _executeAction(actionIds[i], actionData[j]);
            }
            actionIdx += numActions;
        }
    }

    function _executeAction(uint32 actionId, bytes memory actionData) private {
        if (actionId == 0x3eaf5d9f) {
            tick();
        } else
        if (actionId == 0x4f70db79) {
            ActionData_Add memory action = abi.decode(
                actionData,
                (ActionData_Add)
            );
            add(action);
        } else {
            revert("Entrypoint: Invalid action ID");
        }
    }
    
    function add(ActionData_Add memory action) public virtual {
        revert("not implemented");
    }
}
