// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */


struct RowData_Counter {
    int16 value;
}


interface ITables {
    function getCounter() external view returns (RowData_Counter memory);
}
