// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

enum ActionId {
    Move
}

struct ActionData_Move {
    uint8 playerId;
    uint8 direction;
}

interface IActionExecutor {

    event ActionExecuted(uint8 actionId, bytes data);

    function move(ActionData_Move memory action) external;

}
