// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import "codegen/sol/ITables.sol";
import "codegen/sol/IActions.sol";

interface ICore is ITableGetter, IActionExecutor {}
