/* Autogenerated file. Do not edit manually. */

package {{.Package}}

import (
    "reflect"

	"github.com/concrete-eth/archetype/arch"

	{{ range .Imports }}
	{{- if .Name }}{{ .Name }} "{{ .Path }}"
    {{- else }}"{{ .Path }}"{{ end }}
	{{ end }}
)

var ActionsABIJson = contract.ContractABI

var ActionSchemasJson = `{{.Json}}`

var ActionSchemas arch.ActionSchemas

func init() {
    types := map[string]reflect.Type{
        {{- range .Schemas }}
        "{{.Name}}": reflect.TypeOf({{GoActionStructNameFn .Name}}{}),
        {{- end }}
        // "{{$.ArchParams.TickActionName}}": reflect.TypeOf(arch.CanonicalTickAction{}),
    }
    var err error
	if ActionSchemas, err = arch.NewActionSchemasFromRaw(ActionsABIJson, ActionSchemasJson, types); err != nil {
		panic(err)
	}
}

type IActions interface {
    {{- range .Schemas }}
    {{ GoActionMethodNameFn .Name }}(action *{{GoActionStructNameFn .Name}}) error
    {{- end }}
    {{ GoActionMethodNameFn $.ArchParams.TickActionName }}()
}
