/* Autogenerated file. Do not edit manually. */

package {{$.Package}}

import (
    "reflect"

	"github.com/concrete-eth/archetype/arch"

	{{ range $import := $.Imports }}
	{{- if $import.Name }}{{$import.Name}} "{{$import.Path}}"
    {{- else }}"{{$import.Path}}"{{ end }}
	{{ end }}
)

var TablesABIJson = contract.ContractABI

var TableSchemasJson = `{{$.Json}}`

var TableSchemas arch.TableSchemas

func init() {
    types := map[string]reflect.Type{
        {{- range $schema := $.Schemas }}
        "{{$schema.Name}}": reflect.TypeOf({{ GoTableStructNameFn $schema.Name }}{}),
        {{- end }}
    }
    getters := map[string]interface{}{
        {{- range $schema := $.Schemas }}
        "{{$schema.Name}}": datamod.New{{$schema.Name}},
        {{- end }}
    }
    var err error
    if TableSchemas, err = arch.NewTableSchemasFromRaw(TablesABIJson, TableSchemasJson, types, getters); err != nil {
        panic(err)
    }
}
