/* Autogenerated file. Do not edit manually. */

package {{.Package}}

import (
    "reflect"

	"github.com/concrete-eth/archetype/arch"

	{{ range .Imports }}
	{{- if .Name }}{{ .Name }} "{{ .Path }}"
    {{- else }}"{{ .Path }}"{{ end }}
	{{ end }}
)

var TablesABIJson = contract.ContractABI

var TablesSchemaJson = `{{.Json}}`

var TableSpecs arch.TableSpecs

func init() {
    types := map[string]reflect.Type{
        {{- range .Schemas }}
        "{{.Name}}": reflect.TypeOf({{TableStructNameFn .Name}}{}),
        {{- end }}
    }
    getters := map[string]interface{}{
        {{- range .Schemas }}
        "{{.Name}}": mod.New{{.Name}},
        {{- end }}
    }
    var err error
    if TableSpecs, err = arch.NewTableSpecsFromRaw(TablesABIJson, TablesSchemaJson, types, getters); err != nil {
        panic(err)
    }
}
