/* Autogenerated file. Do not edit manually. */

package {{.Package}}

import (
    "github.com/ethereum/go-ethereum/common"
    
    {{ range .Imports }}
	{{- if .Name }}{{.Name}} "{{.Path}}"
    {{- else }}"{{.Path}}"{{ end }}
	{{ end }}
)

var (
	_ = common.Big1
)

{{ if .Comment }}
/*
{{.Comment}}
*/
{{ end }}

{{ range $schema := .Schemas }}
type {{ StructNameFn $schema.Name }} struct{
    {{- range $value := $schema.Values }}
    {{$value.Title}} {{$value.Type.GoType}} `json:"{{$value.Name}}"`
    {{- end }}
}
{{ range $value := $schema.Values }}
func (row *{{ StructNameFn $schema.Name }}) Get{{$value.Title}}() {{$value.Type.GoType}} {
    return row.{{$value.Title}}
}
{{ end }}
{{ end }}
