/* Autogenerated file. Do not edit manually. */

package datamod

import (
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/concrete/codegen/datamod/codec"
	"github.com/ethereum/go-ethereum/concrete/crypto"
	"github.com/ethereum/go-ethereum/concrete/lib"
)

// Reference imports to suppress errors if they are not used.
var (
	_ = crypto.Keccak256
	_ = big.NewInt
	_ = common.Big1
	_ = codec.EncodeAddress
)

// var (
//	PlayersDefaultKey = crypto.Keccak256([]byte("datamod.v1.Players"))
// )

func PlayersDefaultKey() []byte {
	return crypto.Keccak256([]byte("datamod.v1.Players"))
}

type PlayersRow struct {
	lib.IDatastoreStruct
}

func NewPlayersRow(dsSlot lib.DatastoreSlot) *PlayersRow {
	sizes := []int{2, 2, 1}
	return &PlayersRow{lib.NewDatastoreStruct(dsSlot, sizes)}
}

func (v *PlayersRow) Get() (
	x int16,
	y int16,
	health uint8,
) {
	return codec.DecodeSmallInt16(2, v.GetField(0)),
		codec.DecodeSmallInt16(2, v.GetField(1)),
		codec.DecodeSmallUint8(1, v.GetField(2))
}

func (v *PlayersRow) Set(
	x int16,
	y int16,
	health uint8,
) {
	v.SetField(0, codec.EncodeSmallInt16(2, x))
	v.SetField(1, codec.EncodeSmallInt16(2, y))
	v.SetField(2, codec.EncodeSmallUint8(1, health))
}

func (v *PlayersRow) GetX() int16 {
	data := v.GetField(0)
	return codec.DecodeSmallInt16(2, data)
}

func (v *PlayersRow) SetX(value int16) {
	data := codec.EncodeSmallInt16(2, value)
	v.SetField(0, data)
}

func (v *PlayersRow) GetY() int16 {
	data := v.GetField(1)
	return codec.DecodeSmallInt16(2, data)
}

func (v *PlayersRow) SetY(value int16) {
	data := codec.EncodeSmallInt16(2, value)
	v.SetField(1, data)
}

func (v *PlayersRow) GetHealth() uint8 {
	data := v.GetField(2)
	return codec.DecodeSmallUint8(1, data)
}

func (v *PlayersRow) SetHealth(value uint8) {
	data := codec.EncodeSmallUint8(1, value)
	v.SetField(2, data)
}

type Players struct {
	dsSlot lib.DatastoreSlot
}

func NewPlayers(ds lib.Datastore) *Players {
	dsSlot := ds.Get(PlayersDefaultKey())
	return &Players{dsSlot}
}

func NewPlayersFromSlot(dsSlot lib.DatastoreSlot) *Players {
	return &Players{dsSlot}
}
func (m *Players) Get(
	playerId uint8,
) *PlayersRow {
	dsSlot := m.dsSlot.Mapping().GetNested(
		codec.EncodeSmallUint8(1, playerId),
	)
	return NewPlayersRow(dsSlot)
}
